import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {pathToFileURL} from 'node:url';
import {chapters,quiz} from '../public/studyhub/chemistry-notes/content.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE?pathToFileURL(process.env.PLAYWRIGHT_MODULE).href:'playwright');
const root=resolve('public/studyhub');
const server=createServer(async(req,res)=>{try{let p=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(p.endsWith('/'))p+='index.html';const file=resolve(root,'.'+p);if(!file.startsWith(root+sep))throw Error('Outside root');const body=await readFile(file);res.writeHead(200,{'Content-Type':({'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.mjs':'text/javascript'})[extname(file)]||'application/octet-stream'});res.end(body);}catch{res.writeHead(404);res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
const url=`http://127.0.0.1:${server.address().port}/chemistry-notes/`;
const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'msedge',headless:true});
const errors=[];
try{
  await mkdir('tmp/chemistry/review',{recursive:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'light'});
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(url);
  assert.equal(await page.locator('.chapter').count(),7);
  assert.equal(await page.locator('.question').count(),32);
  assert.equal(await page.locator('#progressText').textContent(),'0 / 7');
  assert.equal(await page.locator('#score').textContent(),'已答 0 / 32 · 答對 0 題');
  await page.screenshot({path:'tmp/chemistry/review/desktop.png'});
  await page.locator('[data-complete="foundation"]').check();
  await page.reload();
  assert.equal(await page.locator('#progressText').textContent(),'1 / 7');
  await page.locator('#theme').click();
  await page.reload();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.screenshot({path:'tmp/chemistry/review/dark.png'});
  await page.locator('#theme').click();
  await page.locator('#search').fill('不存在的化學字串');
  assert.equal(await page.locator('.chapter:visible').count(),0);
  assert.equal(await page.locator('#empty').isVisible(),true);
  await page.locator('#search').fill('氫鍵');
  assert.ok(await page.locator('.chapter:visible').count()>0);
  await page.locator('#search').fill('CO2');
  assert.equal(await page.locator('#polarity').isVisible(),true);
  await page.locator('.sidebar a[href="#hybrid"]').click();
  await page.waitForFunction(()=>document.querySelector('#search').value==='');
  assert.equal(await page.locator('#search').inputValue(),'');
  assert.equal(await page.locator('#hybrid .lesson').getAttribute('open'),'');
  await page.locator('#hybrid').screenshot({path:'tmp/chemistry/review/lesson.png'});
  // Deliberately answer the first question incorrectly, all others correctly.
  for(const q of quiz){const f=page.locator(`[data-question="${q.id}"]`);await f.locator(`input[value="${q.id===1?(q.answer+1)%4:q.answer}"]`).check();await f.locator('button').click();assert.equal(await f.locator('.feedback').isVisible(),true);}
  assert.equal(await page.locator('#score').textContent(),'已答 32 / 32 · 答對 31 題');
  await page.locator('#wrongOnly').check();
  assert.equal(await page.locator('.question:visible').count(),1);
  assert.equal(await page.locator('.question:visible').getAttribute('data-question'),'1');
  await page.locator('#resetQuiz').click();
  assert.equal(await page.locator('.question:visible').count(),32);
  assert.equal(await page.locator('.question input:checked').count(),0);
  await page.locator('#resetProgress').click();
  assert.equal(await page.locator('#progressText').textContent(),'0 / 7');
  await page.setViewportSize({width:390,height:844});
  await page.goto(url);
  await page.screenshot({path:'tmp/chemistry/review/mobile.png',fullPage:false});
  await page.locator('#expand').click();
  assert.equal(await page.locator('.lesson[open]').count(),7);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page horizontal overflow at 390px');
  await page.locator('#polarity').scrollIntoViewIfNeeded();
  await page.screenshot({path:'tmp/chemistry/review/mobile-lesson.png'});
  await page.setViewportSize({width:320,height:740});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page horizontal overflow at 320px');
  await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));
  assert.equal(await page.locator('.lesson[open]').count(),7);
  await page.emulateMedia({media:'print'});
  assert.equal(await page.locator('.sidebar').isVisible(),false);
  assert.equal(await page.locator('#forces .lesson-body').isVisible(),true);
  const noJS=await browser.newPage({javaScriptEnabled:false});
  await noJS.goto(url);
  assert.ok((await noJS.locator('body').textContent()).includes('展開 32 題答案與解析'));
  const corrupted=await browser.newPage();
  await corrupted.addInitScript(()=>localStorage.setItem('studyhub-chemistry-v1','{"complete":42}'));
  await corrupted.goto(url);
  assert.equal(await corrupted.locator('#progressText').textContent(),'0 / 7');
  for(const c of chapters){assert.ok(c.body.length>1200);assert.ok(c.body.includes('停下來想一想'));}
  assert.deepEqual(errors,[]);
  console.log('PASS: 7 chapters; all 32 quiz submissions; scoring; incorrect-answer filter; reset; persisted progress/theme; search; hash navigation; 390/320px overflow; print; no-JS notes; malformed storage; zero browser errors.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
